@startuml Use case
left to right direction
skinparam packageStyle rectangle

:Klient: as cl
:XPower Api: as api
:Hub: as hub

rectangle System {
    usecase "Login" as wuc1
    usecase "Logud" as wuc2
    usecase "Tænd / sluk IoT enhed" as wuc3
    usecase "Opret bruger profil" as wuc4
}

cl --> wuc1
cl --> wuc2
cl --> wuc3
cl --> wuc4

wuc1 -- api
wuc2 -- api
wuc4 -- api

wuc3 -- hub

@enduml