@startuml Use case
left to right direction
skinparam packageStyle rectangle

:Klient: as cl
:XPower Api: as api
:Hub: as hub

rectangle System {
    usecase "Login" as wuc1
    usecase "Tilslut IoT til hub" as wuc2
    usecase "Tænd / sluk IoT enhed" as wuc3
    usecase "Fjern IoT enhed fra hub" as wuc4
    usecase "Sæt timer pr. enhed" as wuc5
    usecase "Se overblik for IoT enhed" as wuc6
    usecase "Sæt tænd / sluk ud fra forbrugsmønster" as wuc7
    usecase "Opret bruger profil" as wuc8
    usecase "Tilføj hub under bruger" as wuc9
    usecase "Få pris overblik for el-selskab" as wuc10
}

cl --> wuc1
cl --> wuc2
cl --> wuc3
cl --> wuc4
cl --> wuc5
cl --> wuc6
cl --> wuc7
cl --> wuc8
cl --> wuc9
cl --> wuc10

wuc1 -- api
wuc8 -- api
wuc10 -- api

wuc2 -- hub
wuc3 -- hub
wuc4 -- hub
wuc5 -- hub
wuc6 -- hub
wuc7 -- hub
wuc9 -- hub


@enduml