@startuml Hub status action SD diagrams
title Send Status from hub

ServerController -> IStatusMessageActions: Execute
IStatusMessageActions -> IDeviceManager: Get offline devices
IDeviceManager -> IStatusMessageActions: Return offline devices
IStatusMessageActions -> ServerController: Publish offline devices

@enduml