@startuml APPLICATION

class HubSearcherComponent{
    ssid : string
    passphrase : string
    device : any

    HubSearcherComponent(_zone: NgZone, _hubConnService: HubConnServiceService) : void
    connected(value: BluetoothRemoteGATTCharacteristic) void
    connect() : void
    selectDevice() : void
    sendinput() : void
    onSsidKey(event : any) : void
    onPassPhraseKey(event: any) : void
}

class HubConnServiceService{
    GATT_CHARACTERISTIC_CONNECTION : string
    GATT_PRIMARY_SERVICE : string
    character : any

    HubConnServiceService(ble: BluetoothCore)
    getCharConnect() : BluetoothRemoteGATTCharacteristic
    getCharacter() : BluetoothRemoteGATTCharacteristic
    getDevice() : BluetoothDevice
}

HubSearcherComponent *-- HubConnServiceService

@enduml