@startuml API

interface IGetPrice
{
    Getprice(Datetime from, Datetime to, Company company) : T
}

class PriceController 
{

}

class Price
{
    Amount : double
}

enum Company{
    Unknown,
    ElCompany1,
    ElCompany2
}

interface IUserCrud
{
    CreateUser(UserCreate : UserCreateDTO) : T  
    GetUser(userID : int ) : T
    GetUserHubs(userID : int) : List<T>
    GetHomeUserHubs(homeUserID : int) : List<T>
    UpdateUser(userID : int, username : string) : T
    DeleteUser(userID : int ) : void
}

class UserController
{

}

class UserService
{

}

class UserCreateDTO
{
    Username : string
    Password : string
}

class User
{
    Username : string,
    ID : int
}


interface IHubCrud
{
    CreateHub(hubCreate : HubCreate) : T  
    GetHub(hubID : int ) : T
    UpdateHub(hubID : int, displayname : string) : T
    DeleteUser(hubID : int ) : void
}

class HubController
{

}

class HubService
{

}

class HubProvider
{

}

class HubCreate
{
    UID : string
}

class Hub
{
    ID : int
    UID : string
    DisplayName : string
    HomeID : int
}

PriceController <|.. IGetPrice
IGetPrice <|-- Price
IGetPrice <|-- Company

UserController <|.. IUserCrud
UserService <|.. IUserCrud
UserProvider <|.. IUserCrud
UserService <|-- User
UserController <|-- UserCreateDTO


HubController <|.. IHubCrud
HubService <|.. IHubCrud
HubProvider <|.. IHubCrud
HubService <|-- Hub
HubController <|-- HubCreate

@enduml