# This is a basic workflow to help you get started with Actions

name: Projects tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
        
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest]
        python-version: ['3.9']
        dotnet-version: ['6.0']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          python-version: '3.9'
          dotnet-version: '6.0'
          check-latest: true
          
      - name: Py version log
        run: python --version
      # Runs a single command using the runners shell
      - name: Starting git action
        run: echo Starting git action

      # Runs a set of commands using the runners shell
      - name: Running hub python unit test
        run: python ./source/hub/tests/test_main.py
        
      - name: Running grpc unit tests 
        run: |
             cd source/cloudserver/iot-handler/XPowerIoTHandler
             dotnet test

      - name: Running Hub CSharp tests
        run: |
            cd source/hub/tests/CSharpTests
            dotnet test
        
      - name: Running webapi unit tests
        run: |
            cd source/cloudserver/webapi/XPowerApi
            dotnet test
